app/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("pages/", include("pages.urls")),
]

app/pages/urls.py
from django.urls import path
from . import views, ui_views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("manage-homes/", views.manage_homes_view, name="manage_homes"),
    path("logout/", views.logout_view, name="logout"),
    
    # UI Prototypes
    path("ui/dashboard/", ui_views.ui_dashboard, name="ui_dashboard"),
    path("ui/home-setup/", ui_views.ui_home_setup, name="ui_home_setup"),
    path("ui/appliances/", ui_views.ui_appliances, name="ui_appliances"),
    path("ui/appliance/<uuid:id>/", ui_views.ui_appliance_detail, name="ui_appliance_detail"),
]

app/pages/models.py
import uuid

from django.core.validators import MinLengthValidator
from django.db import models
from datetime import date

#Left, is what is stored, I capitalized the right to be pretty
INTERVAL_CHOICES = [
    ("daily", "Daily"),
    ("weekly", "Weekly"),
    ("monthly", "Monthly"),
    ("quarterly", "Quarterly"),
    ("yearly", "Yearly"),
]
# use this in build upcoming occurrences
INTERVAL_DAY_MAP = {
    "daily": 1,
    "weekly": 7,
    "monthly": 30,
    "quarterly": 91,
    "yearly": 365,
}

#choices for asset category
CATEGORY_CHOICES = [
    ("General", "General"),
    ("Appliance", "Appliance"),
    ("Furniture", "Furniture")
]

#choices for brand could be modified
BRAND_CHOICES = [
    ("GE", "GE"),
    ("LG", "LG"),
    ("Whirlpool", "Whirlpool"),
    ("Frigidaire", "Frigidaire"),
    ("Samsung", "Samsung"),
    ("Bosch", "Bosch"),
    ("KitchenAid", "KitchenAid"),
    ("Maytag", "Maytag"),
    ("Kenmore", "Kenmore"),
    ("Other", "Other"),
    ("Unknown", "Unknown"),
]


class Home(models.Model):
    home_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=128)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=64, blank=True)
    zip_code = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.name

# The user will be what ultimately determines what assets are on their dashboard and what tasks they need to do, etc.
class AppUser(models.Model):
    username = models.CharField(
        primary_key=True,
        max_length=20,
        validators=[MinLengthValidator(5)],
    )
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=128)
    homes = models.ManyToManyField(
        "Home",
        through="HomeUserConnection",
        related_name="users",
        blank=True,
    )

    def __str__(self):
        return f"{self.username} ({self.email})"

#Maps each user(s) to their homes
class HomeUserConnection(models.Model):
    home = models.ForeignKey(Home, on_delete=models.CASCADE, related_name="home_user_connections")
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="home_user_connections")

    #Marks that this is a composite key to prevent duplicate connections
    class Meta:
        unique_together = ("home", "user")

    def __str__(self):
        return f"{self.user.username} is connected to this home: {self.home.name}"


# The rooms primary id is a uuid that is automatically generated on creation
# The room is matched to the particular home, when the home is deleted, the room is deleted
# I just set the max length to an arbitrary number, but it should be fine for most instances
class Room(models.Model):
    room_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    home = models.ForeignKey(Home, on_delete=models.CASCADE, related_name="rooms")
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.name} ({self.home.name})"

# I did the same uuid pk as the room
# There is also a foreign key to the room, so that we can track which room the asset is in to make sure it appears correctly
# I set arbitrary max length for name and brand fields
# When room is deleted, assets in that room are deleted
class Asset(models.Model):
    asset_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64)
    brand = models.CharField(max_length=64, choices=BRAND_CHOICES, blank=True)
    model_number = models.CharField(max_length=64, blank=True)
    #name = models.CharField(max_length=64)
    #brand = models.CharField(max_length=64, blank=True) # THIS USED AS MANUFACTURER. Could eventually be a constanstant as the other choices above are or something.
    #model_number = models.CharField(max_length=64, blank=True)
    category = models.CharField(max_length=32, choices=CATEGORY_CHOICES, default="general")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="assets")

    def __str__(self):
        name = self.name or "Unnamed asset"
        room_name = self.room.name if self.room else "Unassigned room"
        return f"{name} ({room_name})"

    @property
    def consumable_name(self):
        #grabs consumable or part number for the ui to display
        # this is used in dashboard.html to show what part an appliance needs.
        for consumable in self.consumables.all():
            if consumable.name:
                return consumable.name
            if consumable.details and consumable.details.part_number:
                return consumable.details.part_number
        return None

# The task id is a uuid that is automatically generated on creation
# The task is matched to the particular asset, when the asset is deleted, the task is deleted
# The task can also be tied to a room, when the room is deleted, the task is deleted
# Might need to remove the completed
class Task(models.Model):
    INTERVAL_CHOICES = INTERVAL_CHOICES
    task_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64)
    interval = models.CharField(max_length=16, choices=INTERVAL_CHOICES, blank=True)
    next_due_date = models.DateField(null=True, blank=True)
    last_completed_date = models.DateField(null=True, blank=True)
    #completed = models.BooleanField(default=False)
    home = models.ForeignKey(Home, on_delete=models.CASCADE, related_name="tasks", null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="tasks", null=True, blank=True)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, related_name="tasks", null=True, blank=True)
    consumable = models.ForeignKey("Consumable", on_delete=models.CASCADE, related_name="tasks", null=True, blank=True)

    
#Calculating the number of days between today and next due date
    @property
    def days_until_due(self):
        if not self.next_due_date:
            return None
        delta = self.next_due_date - date.today()
        return delta.days

    def __str__(self):
        # Use the asset name if available for display.
        asset_name = (
            self.asset.name if self.asset else None
        )
        location = (
            asset_name if asset_name else self.room.name if self.room else self.home.name if self.home else "general"
        )
        return f"{self.name} ({location})"

# The consumable id is a uuid that is automatically generated on creation
# The consumable is matched to the particular task, when the task is deleted, the consumable is deleted
# The part number is optional, but if it is present, it will be displayed in the admin page. I think this is what we can use API to get the price of the consumable
# The estimated cost is optional, but if it is present, it will be displayed in the admin page
class Consumable(models.Model):
    consumable_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64, blank=True)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, related_name="consumables")

    def __str__(self):
        if self.name:
            return self.name
        if self.details and self.details.part_number:
            return self.details.part_number
        return f"Consumable for {self.asset.name}"

# Details for a consumable. Allows for  
class ConsumableDetails(models.Model):
    consumable = models.OneToOneField("Consumable", on_delete=models.CASCADE, related_name="details")
    part_number = models.CharField(max_length=64, blank=True)
    estimated_cost = models.DecimalField(max_digits=9, decimal_places=2, default=0, blank=True)
    retail_url = models.URLField(blank=True)

    # Null for consumable details not made by a user
    owner = models.ForeignKey(AppUser, null=True, blank=True, on_delete=models.CASCADE, related_name="custom_consumable_details")

    def __str__(self):
        return self.part_number or "Unnamed Consumable"

# The log id is a uuid that is automatically generated on creation
# The log is matched to the particular task, when the task is deleted, the log is deleted
# The completion date is optional, but if it is present, it will be displayed in the admin page
# The cost is optional, but if it is present, it will be displayed in the admin page
# The notes are optional, but if they are present, they will be displayed in the admin page
# The completion date of this could be what resets the duration of the task
class Log(models.Model):
    log_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    completion_date = models.DateField(null=True, blank=True)
    cost = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    notes = models.TextField(blank=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="logs")

    def __str__(self):
        date = self.completion_date or "pending"
        return f"{self.task.name} on {date}"

app/pages/templates/base.html
{% load tailwind_tags %}
<!doctype html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <title>Upkeep</title>
  </head>
  {# The base to appear on every page!!! #}
  <body class="bg-[#f5fcff] min-h-screen flex flex-col">
    <header class="bg-cyan-900 border-b border-b-gray-400">
      <div class="w-full px-6 py-4 flex items-center justify-between">
        <a href="/" class="text-xl font-bold text-white">Upkeep</a>
        <div class="flex items-center gap-3">
            {#SHow user name when logged in, else the login/register buttons#}
          {% if request.session.username %}
            <a href="/pages/dashboard/" class="px-3 py-1 underline text-white">Dashboard</a>
            <a href="/pages/manage-homes/" class="px-3 py-1 underline text-white">Manage Homes</a>
            <span class="text-white">{{ request.session.username }}</span>
            <a href="/pages/logout/" class="px-3 py-1 border border-gray-400 text-white">Logout</a>
          {% else %}
            <a href="/pages/login/" class="px-3 py-1 border border-gray-400 text-white">Login</a>
            <a href="/pages/register/" class="px-3 py-1 border border-gray-400 text-white">Register</a>
          {% endif %}
        </div>
      </div>
    <div>
        {% if request.session.username and home %}
            <div class="w-full px-6 pb-4">
                <div class="flex flex-wrap items-center justify-between gap-4 text-white">
                    <div>
                        <p class="text-xs uppercase tracking-wide">Current home</p>
                        <p class="text-lg font-medium">{{ home.name }}</p>
                        {% if home.address or home.city or home.state or home.zip_code %}
                            <p class="text-xs">
                                {{ home.address }}
                                {% if home.city %}<br/>{{ home.city }}{% endif %}
                                {% if home.state %}, {{ home.state }}{% endif %}
                                {% if home.zip_code %} {{ home.zip_code }}{% endif %}
                            </p>
                        {% endif %}
                    </div>
                    <form method="post" action="{% url 'dashboard' %}" class="flex items-center gap-2 text-sm">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="switch-home">
                        <select name="home_id" class="border px-2 py-1 text-white">
                            {% for item in homes %}
                                <option value="{{ item.home_id }}" {% if item.home_id == home.home_id %}selected{% endif %}>
                                    {{ item.name }}
                                </option>
                            {% endfor %}
                        </select>
                        <button type="submit" class="border px-3 py-1 bg-green-400 text-black">Switch</button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>

    </header>

    {#Show login/logout messages#}
    {% if messages %}
        <div class="fixed bottom-4 right-4 flex flex-col items-end gap-2 w-full max-w-sm px-4">
            {% for message in messages %}
                <div class="messages shadow-lg border px-4 py-3 text-black
                    {% if message.tags == 'success' %} border-green-500 bg-green-50
                    {% elif message.tags == 'error' %} border-red-500 bg-red-50
                    {% else %} border-gray-400 bg-white {% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <main class="grow p-4">
        {% block content %}{% endblock %}
    </main>

  <script>
      {#once the page has loaded, remove any messages after 3 seconds#}
      document.addEventListener('DOMContentLoaded', () => {
          const messages = document.querySelectorAll('.messages');
          messages.forEach(message => {
              setTimeout(() => message.remove(), 3000);
          })
      })
  </script>
  </body>
</html>

app/pages/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
<div class="max-w-5xl mx-auto space-y-5">
  <header class="border-b border-black pb-4">
    <h1 class="text-2xl text-black">Dashboard</h1>
    <p class="text-md text-black">Welcome, {{ request.session.username }}.</p>
  </header>

    {#Global stats#}
  <section class="grid grid-cols-3 gap-4">
    <div class="border rounded p-3 bg-[#dbf3fa] text-black">
      <p class="text-xs uppercase text-black">Rooms</p>
      <p class="text-3xl font-bold">{{ rooms.count }}</p>
      <p class="text-sm text-black">total</p>
    </div>
    <div class="border text-black rounded p-3 bg-[#dbf3fa]">
      <p class="text-xs uppercase text-black">Assets</p>
      <p class="text-3xl font-bold text-black">{{ assets.count }}</p>
      <p class="text-sm text-black">in view</p>
    </div>
    <div class="border text-black rounded p-3 bg-[#dbf3fa]">
      <p class="text-xs uppercase ">Tasks</p>
      <p class="text-3xl font-bold ">{{ tasks.count }}</p>
      <p class="text-sm ">linked to these rooms</p>
    </div>
  </section>

    {#Room n assets overview#}
  <section class="grid text-black gap-4 grid-cols-2">
    <div class="border text-black rounded bg-[#dbf3fa] p-4">
      <p class="text-md mb-2">Room list</p>
      {% if rooms %}
        <ul class="space-y-1 max-h-64 overflow-y-auto text-sm">
          {% for room in rooms %}
            {#fyi, justify between within container puts them on separate ends#}
            <li class="flex justify-between">
              <span>{{ room.name }}</span>
              <span class="text-xs">{{ room.assets.count }} assets</span>
              <div>
                {# button to sort by room #}
                <form method="POST"
                action="{% url 'dashboard'%}">
                {% csrf_token %}
                <input type="hidden" name="action" value="sort-room">
                <input type="hidden" name="room_id" value="{{room.room_id}}">
                <button type="submit" title="Sort Room" class="text-xs text-yellow-400">Sort By</button>
                </form>
                {# button to delete room #}
                <form method="POST"
                action="{% url 'dashboard'%}"
                onsubmit="return confirm('Want to delete this room?')">
                {% csrf_token %}
                <input type="hidden" name="action" value="delete-room">
                <input type="hidden" name="room_id" value="{{room.room_id}}">
                <button type="submit" title="Delete Room" class="text-xs text-red-400">Delete

                </button>
                </form>
              </div>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-xs">No rooms yet.</p>
      {% endif %}
    </div>
    <div class="border rounded bg-[#dbf3fa] p-4">
      <p class="text-md mb-2">Assets</p>
      {% if assets %}
        <ul class="space-y-1 text-sm max-h-64 overflow-y-auto">
          {% for asset in assets %}
            {#last makes sure that the last item does not get the styling#}
            <li class=" text-black flex justify-between items-start border-zinc-400 border-b pb-2 last:border-none">
              <div>
                <div class="font-medium text-black">{{ asset.name }}</div>
{#                Display if it has a brand/consumable#}
                {% if asset.brand %}
                  <div class="text-xs text-black">Brand: {{ asset.brand }}</div>
                {% endif %}
                {% if asset.consumable_name %}
                  <div class="text-xs text-black">
                    Consumable: {{ asset.consumable_name }}
                  </div>
                {% endif %}
              </div>
              <div class="text-xs text-black">Room: {{ asset.room.name }}</div>


              <div class = "flex flex-col items-end space-y-2">

                {# button to sort by asset #}
                <form method="POST"
                action="{% url 'dashboard'%}">
                {% csrf_token %}
                  <input type="hidden" name="action" value="sort-asset">
                  <input type="hidden" name="asset_id" value="{{asset.asset_id}}">
                  <button type="submit" title="Sort Asset" class="text-xs text-yellow-400">Sort By</button>
              </form>
                {#Deleting asset#}
                <form method="POST" action="{% url 'dashboard'%}"
                onsubmit="return confirm('Want to delete {{asset.name}}?')">
                {% csrf_token %}
                  <input type="hidden" name="action" value="delete-asset">
                  <input type="hidden" name="asset_id" value="{{asset.asset_id}}">
                  <button type="submit" title="Delete Asset" class="text-xs text-red-400">Delete
                  </button>
                </form>
              </div>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-xs text-black">Select or create a room to see assets.</p>
      {% endif %}
    </div>
  </section>

    {#Tasks and due soon section#}
  <section class="grid text-black gap-4 grid-cols-2">
    <div class="border rounded bg-[#dbf3fa] p-4">
      <p class="text-sm mb-2">Tasks</p>
      {% if tasks %}
{#          Overflow turns the area into scroll once content taks up max height#}
        <ul class="space-y-2 text-sm max-h-64 overflow-y-auto pr-2">
          {% for task in tasks %}
            <li class="border-b pb-2 last:border-none">
              <div class="font-medium">{{ task.name }}</div>
              <div class="text-xs text-black">Location: {% if task.asset %}{{ task.asset.name }}{% elif task.room %}{{ task.room.name }}{% elif task.home %}{{ task.home.name }}{% else %}General{% endif %}</div>
              <div class="text-xs text-black">
                Interval: {% if task.interval %}{{ task.get_interval_display }}{% else %}Not set{% endif %}
              </div>
              <div class="text-xs text-black">Status: TODO....</div>
              <div class="flex justify-end mt-2">
                <form method="POST" action="{% url 'dashboard' %}">
                  {% csrf_token %}
                  <input type="hidden" name="action" value="delete-task">
                  <input type="hidden" name="task_id" value="{{ task.task_id }}">
                  <input type="hidden" name="return_room" value="{{ selected_room_id }}">
                  <button type="submit" class="text-xs text-red-400">Delete</button>
                </form>
              </div>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-xs text-black">Add a task to track maintenance or chores.</p>
      {% endif %}
    </div>
    <div class="border rounded bg-[#dbf3fa] p-4">
      <p class="text-sm  mb-2">Due soon</p>
      {% if due_soon_tasks %}
        <ul class="space-y-2 text-sm max-h-64 overflow-y-auto pr-2">
          {% for task in due_soon_tasks %}
            <li class="border-b pb-2 last:border-none flex justify-between items-start text-black">
              <div>
                <div class="font-medium">{{ task.name }}</div>
                <div class="text-xs text-black">Assigned: {% if task.asset %}{{ task.asset.name }}{% elif task.room %}{{ task.room.name }}{% elif task.home %}{{ task.home.name }}{% else %}General{% endif %}</div>
                <div class="text-xs text-black">
                  Next due: {% if task.next_due_date %}{{ task.next_due_date|date:"M. d, Y" }}{% else %}TBD{% endif %}
                </div>
              </div>
              <div class = "text-right flex flex-col items-end">
                {% if task.days_until_due != None %}
                  {% if task.days_until_due <= 4 %}
                    <span class="px-2 py-0.5 rounded bg-red-500 text-white font-bold text-[10px] animate-pulse">URGENT</span>
                  {% elif task.days_until_due <= 7 %}
                      <span class="px-2 py-0.5 rounded bg-amber-500 text-white font-bold text-[10px]">SOON</span>
                  {% elif task.days_until_due <= 14 %}
                      <span class="px-2 py-0.5 rounded bg-white text-black border border-gray-300 text-[10px]">UPCOMING</span>
                  {% endif %}
                  <span class="text-[10px] block mt-1">{{ task.days_until_due }} days left</span>
                {% endif %}
              </div>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-xs text-black">Tasks become due after they are added here.</p>
      {% endif %}
    </div>
  </section>

    {#Activity log secton. Takes up full width when max not specified#}
  <section class="text-black border rounded bg-[#dbf3fa] p-4">
    <p class="text-sm mb-2">Activity log</p>
    {% if logs %}
      <ul class="space-y-2 max-h-64 overflow-y-auto text-sm">
        {% for log in logs %}
          <li class="border-b pb-2 last:border-none">
            <div class="font-medium">{{ log.task.name }}</div>
            <div class="text-xs text-black">
              Completed: {% if log.completion_date %}{{ log.completion_date }}{% else %}Pending{% endif %}
            </div>
            <div class="text-xs text-black">
              Cost: {% if log.cost %}{{ log.cost }}{% else %}—{% endif %}
            </div>
            <div class="text-xs text-black">
              Notes: {% if log.notes %}{{ log.notes }}{% else %}No notes{% endif %}
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-xs text-black">Logs show task history once recorded</p>
    {% endif %}
  </section>

</div>
{% endblock %}

app/pages/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="max-w-md mx-auto">
  <h1 class="text-2xl text-black mb-4">Login</h1>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label class="block text-black mb-1" for="username">Username</label>
      <input class="w-full border border-gray-500 bg-gray-800 px-2 py-1" id="username" name="username" type="text" required />
    </div>
    <div class="mb-4">
      <label class="block text-black mb-1" for="password">Password</label>
      <input class="w-full border border-gray-500 bg-gray-800 px-2 py-1" id="password" name="password" type="password" required />
    </div>
    <button class="px-4 py-1 border border-gray-400 bg-black" type="submit">Login</button>
  </form>
</div>
{% endblock %}

app/pages/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="max-w-md mx-auto">
  <h1 class="text-2xl text-black mb-4">Register</h1>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label class="block text-black mb-1" for="username">Username</label>
      <input class="w-full border border-gray-500 bg-gray-800 px-2 py-1 " id="username" name="username" type="text" minlength="5" maxlength="20" required />
      <p class="text-sm text-black mt-1">5 to 20 characters.</p>
    </div>
    <div class="mb-3">
      <label class="block text-black mb-1" for="email">Email</label>
      <input class="w-full border border-gray-500 bg-gray-800 px-2 py-1 " id="email" name="email" type="email" required />
    </div>
    <div class="mb-4">
      <label class="block text-black mb-1" for="password">Password</label>
      <input class="w-full border border-gray-500 bg-gray-800 px-2 py-1 " id="password" name="password" type="password" required />
    </div>
    <button class="px-4 py-1 border border-gray-400 bg-black" type="submit">Create Account</button>
  </form>
</div>
{% endblock %}